name: todo_api_shelf
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  lints: ^5.0.0
  test: ^1.24.0
